Repository aws-samples/aws-cdk-examples, pull requests merged in 2023-08, with the labels that each got.

#580 feat(csharp): Add API Gateway Lambda Dynamo Example
  csharp/README.md
  csharp/api-cors-lambda-crud-dynamodb/README.md
  csharp/api-cors-lambda-crud-dynamodb/cdk.json
  csharp/api-cors-lambda-crud-dynamodb/src/ApiCorsLambdaCrudDynamodb.sln
  csharp/api-cors-lambda-crud-dynamodb/src/ApiCorsLambdaCrudDynamodb/ApiCorsLambdaCrudDynamodb.csproj
  csharp/api-cors-lambda-crud-dynamodb/src/ApiCorsLambdaCrudDynamodb/ApiCorsLambdaCrudDynamodbStack.cs
  csharp/api-cors-lambda-crud-dynamodb/src/ApiCorsLambdaCrudDynamodb/Extensions.cs
  csharp/api-cors-lambda-crud-dynamodb/src/ApiCorsLambdaCrudDynamodb/GlobalSuppressions.cs
  csharp/api-cors-lambda-crud-dynamodb/src/ApiCorsLambdaCrudDynamodb/Program.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/Create/Create.csproj
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/Create/Dockerfile
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/Create/Function.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/DeleteOne/DeleteOne.csproj
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/DeleteOne/Dockerfile
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/DeleteOne/Function.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/DynamoItemRepository/DynamoDBItemRepository.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/DynamoItemRepository/DynamoItemRepository.csproj
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/DynamoItemRepository/IDynamoItemRepository.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/DynamoItemRepository/ItemModel.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/GetAll/Dockerfile
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/GetAll/Function.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/GetAll/GetAll.csproj
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/GetOne/Dockerfile
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/GetOne/Function.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/GetOne/GetOne.csproj
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/UpdateOne/Dockerfile
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/UpdateOne/Function.cs
  csharp/api-cors-lambda-crud-dynamodb/src/Lambdas/UpdateOne/UpdateOne.csproj
Labels: language/dotnet

#594 feat(csharp): EC2 Instance Creation with CDK
  csharp/ec2-instance/.gitignore
  csharp/ec2-instance/README.md
  csharp/ec2-instance/cdk-key.pem
  csharp/ec2-instance/cdk.json
  csharp/ec2-instance/src/Ec2Instance.sln
  csharp/ec2-instance/src/Ec2Instance/Ec2Instance.csproj
  csharp/ec2-instance/src/Ec2Instance/Ec2InstanceStack.cs
  csharp/ec2-instance/src/Ec2Instance/GlobalSuppressions.cs
  csharp/ec2-instance/src/Ec2Instance/Program.cs
  csharp/ec2-instance/src/configure.sh
Labels: language/dotnet, pr/needs-review

#612 feat: Added sagemaker multimodel endpoint example
  python/sagemaker-multimodel-endpoint/LICENSE
  python/sagemaker-multimodel-endpoint/README.md
  python/sagemaker-multimodel-endpoint/app.py
  python/sagemaker-multimodel-endpoint/cdk.json
  python/sagemaker-multimodel-endpoint/docker/Dockerfile
  python/sagemaker-multimodel-endpoint/docker/dockerd-entrypoint.py
  python/sagemaker-multimodel-endpoint/docker/model_handler.py
  python/sagemaker-multimodel-endpoint/examples/download_models.py
  python/sagemaker-multimodel-endpoint/examples/invoke_endpoint.py
  python/sagemaker-multimodel-endpoint/images/architecture.png
  python/sagemaker-multimodel-endpoint/models/.gitkeep
  python/sagemaker-multimodel-endpoint/requirements.txt
  python/sagemaker-multimodel-endpoint/sagemaker_multimodel_endpoint/__init__.py
  python/sagemaker-multimodel-endpoint/sagemaker_multimodel_endpoint/sagemaker_multimodel_endpoint_stack.py
Labels: language/python
